### ISSUE TITLE
classFactory() method error with 3.4.13

### ISSUE THREAD

**Issue by SpatialNit** [gacarrillor/CopyLayersAndGroupsToClipboard#2]
Error appeared as below.
Couldn't load plugin 'CopyLayersAndGroupsToClipboard' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'copyLayersAndGroupsToClipboard' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Narrowneck/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CopyLayersAndGroupsToClipboard\__init__.py", line 32, in classFactory
    from copyLayersAndGroupsToClipboard import CopyLayersAndGroupsToClipboard
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'copyLayersAndGroupsToClipboard'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.13-Madeira Madeira, 567300ccf1 
regards

**Comment by gacarrillor** [comment]
This is a QGIS v2 plugin. 
Its functionality is already in QGIS core for v3. Right click on a layer and you'll get copy/paste options.

**Comment by SpatialNit** [comment]
Excellent- Thankyou.

**Comment by gacarrillor** [comment]
You're welcome!
